# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    git submodule update --init --recursive
  displayName: 'Update submodules (main fluentmigrator repo)'

# If installing docfx fails due to missing .NET SDK, update global.json version to match the one available in the current ubuntu-latest
- script: |
    dotnet tool install -g docfx --version 2.77.0
  displayName: 'Install dotnet tool DocFX'

- script: |
    docfx metadata docfx.json
    docfx build docfx.json
  displayName: 'Run DocFX build'

- task: ArchiveFiles@2
  displayName: 'Archive _site folder'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/_site'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: 'site.zip'
    replaceExistingArchive: true

- task: CopyFiles@2
  displayName: 'Copy output to build artifacts'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: 'site.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
